[build]
target = "aarch64-none-custom.json"

[target.aarch64-none-custom]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "compiler_builtins"]